### ISSUE TITLE
Expose containments

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#326]
Blocking #193 

The containment hierarchy need to be worked out and exposed to the backend. 
https://epidemicforecasting.slack.com/archives/C010KK204TG/p1585591422017800

### Todo
- [ ] Agreement over the category hierarchy (people: Jan Kulveit?)
- [ ] Agreement over display and styling of the categories
- [ ] Data wrangling and exposing to frontend

### Data needed for the frontend (suggestion)
**NB: There is a new suggestion below**
Measure category hierarchy, array of records:
- `id` canonical identifier (e.g `schools`)
- `label` the label to be displayed on the left  (e.g. `Schools`)
- `long_name` can be the name of the tag in notion, might be displayed on hover/select (e.g. `Schools and universities`)
- `parent` for the hierarchy, optional field, refers to `id`

Timeline for each country. This is a record, keys refer to `measure_id` and the values are lists of measure mutations (see below). Every measure has a `intensity` parameter which is assumed to start at 0.

A measure mutation is a record with:
- `date` date on which the state change happend (e.g. `2020-2-20`)
- `label` short new state description i.e. (e.g. `closed` this will be displayed on the bar/hover)
- `intensity` float in [0,1], 0 means the measure is not active, and 1 means the measure is active. 
- `description` long description to be displayed on selection
- a list of all notion data (i.e. tagged measures) that went into this
- ... any other relevant fields

Rendering: For each country we render the the measures for which there are mutations/there is a corresponding key. More intense measures have a more intense color. On hover the measure label is displayed. On click we can display the description

**Comment by mathijshenquet** [comment]
### Data needed for the frontend (suggestion 2)
Measure category hierarchy, array of records:
- `id` canonical identifier (e.g `schools`)
- `label` the label to be displayed on the left  (e.g. `Schools`)
- `long_name` can be the name of the tag in notion, might be displayed on hover/select (e.g. `Schools and universities`)
- `kind: "set" | "linear"` - `linear` means that the measures are linearly ordered so that more stingent measures subsume less stingent mesures, `set` means that the measures in this category do not do this.
- **pushed back to later commit** `parent` for the hierarchy, optional field, refers to `id` 

Timeline for each country. This is a record, keys refer to `measure_id` and the values are lists of measure mutations (see below). Every measure has a `intensity` parameter which is assumed to start at 0.

A measure info is a record with:
- `date` date on which the state change happend (e.g. `2020-2-20`)
- `end_date` only applicable when `measure.kind = "set"`.
- `label` short new state description i.e. (e.g. `closed` this will be displayed on the bar/hover)
- `intensity` float in [0,1], 0 means the measure is not active, and 1 means the measure is active (only appicable if `measure.kind == 'linear'`.
- `description` long description to be displayed on selection
- a list of all notion data (i.e. tagged measures) that went into this
- ... any other relevant fields

Rendering: For each country we render the the measures for which there are mutations/there is a corresponding key. More intense measures have a more intense color. On hover the measure label is displayed. On click we can display the description

**Comment by wolverdude** [comment]
Quick status update: I see why this task has been languishing for a while. It's deceptively huge. Based on what I've seen, it'll probably take me most of the week to complete.

Mathijs and David helped me understand what all the notebooks were doing and get the context for where the data is coming from. The current steps are:

- [ ] Fetch & transform tags from Notion (mostly done)
- [ ] Fetch & transform countermeasures from Notion using the tag data
- [ ] Finalize API spec, compile & deploy files to GCS

Further steps once that MVP is finished:

- [ ] Create script to sync survey results to Notion countermeasure records
- [ ] Integrate data from Oxford countermeasures DB

**Comment by mathijshenquet** [comment]
Thanks Jonathan, I also thought that this one was going to be quite difficult so I really appreciate that you are looking into it. If you could use any help please feel free to ask.

**Comment by wolverdude** [comment]
@mathijshenquet, how about this JSON format for the tags?

```graphql
{
  [tag_category_name]: {
    [tag_feature_name]: {
      [tag_name]: {
        description,
        quantity,
        aggregation
      }
    }
  }
}
```

Example:

```json
{
  "Isolation": {
    "Symptomatic isolation - targeted": {
      "contact isolation - symptoms": {
        "description": "Close contacts of confirmed cases directed to isolate if they have symptoms (i.e. more than 15 minutes of contact in the last 7 days) for at least 14 days",
        "quantity": 1.0,
        "aggregation": "max"
      }
    }
  }
}
```

I figured these nested objects would be helpful in showing how to group the containment measures in the display, but it could be better just to store `category` and `feature` within the tag objects and key them by tag name, since the frontend really only uses this data when it already has a specific containment measure it wants to display. I actually lean toward that second option, personally.

The other question I have is about the `quantity` key. Along with `aggregation`, this tells the frontend how to group different tags within the same feature. It would also be nice to interpolate `quantity` into the description field in some places. But `quantity` isn't available for all tags because some of them use data from the containment measure record. Maybe it's best just to serve all quantities with the measures and not the tags?

**Comment by mathijshenquet** [comment]
I agree that the second option makes more sense. In general I think that JSON keys should mostly be known values and not carry information themselves unless you are going definitely going to query the object by this key. This is because we mostly want to demarshallIng the data anyway and iterating over objects is kind of akward in JS.

**Comment by wolverdude** [comment]
Okay. Preliminarily, I think I'll drop `quantity` and send it up with the containment measures instead. I can change it later if it turns out we need it.

Here's an example of the fully-formed JSON format. I did not include a `regions` layer because the data is not region-specific.

```json
{
  "created": "2020-04-14T23:32:35.388824",
  "created_by": "Jonathan Wolverton",
  "comment": null,
  "data": {
    "containment_tags": {
      "cluster isolation - symptoms": {
        "category": "Isolation",
        "feature": "Symptomatic isolation - blanket",
        "name": "cluster isolation - symptoms",
        "description": "Entire districts or large groups (e.g. every member of a church) directed to isolate if they have symptoms for at least 14 days",
        "aggregation": "max"
      },
      "blanket isolation - symptoms": {
        "category": "Isolation",
        "feature": "Symptomatic isolation - blanket",
        "name": "blanket isolation - symptoms",
        "description": "Entire cities or countries directed to isolate if people have symptoms (as in previous levels, this must be a message to the effect \"if you experience these symptoms, you are required/expected to stay in your home for 14 days\" - \"if you are sick, don't come to work\" does _not_ qualify)",
        "aggregation": "max"
      },
      "contact isolation - no symptoms": {
        "category": "Isolation",
        "feature": "Asymptomatic isolation - targeted",
        "name": "contact isolation - no symptoms",
        "description": "close contacts (i.e. more than 15 minutes of contact in the last 7 days) isolated for at least 14 days",
        "aggregation": "max"
      }
    }
  }
}
```

**Comment by hnykda** [comment]
Can we close this?
